[application]

[web.app]

# HTML title tag content
title = "Buddy Up"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "io.alltohim"
publisher = "zerodeviation"
icon = [
   "icons/icon_32x32.png",
   "icons/icon_128x128.png",
   "icons/icon_128x128@2x.png",
   "icons/icon.icns",
   "icons/icon.ico"
]
category = "Utility"
short_description = "Pair up people."
long_description = "Pair up people."

[bundle.windows]
icon_path = ".\\icons\\icon.ico"
tsp = true
webview_install_mode = { OfflineInstaller = { silent = false } }
allow_downgrades = true

