[package]
name = "buddy-up"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
comfy-table = "7.1.4"
csv = "1.3.1"
env_logger = "0.11.6"
genetic_algorithm = "0.18.1"
glob = "0.3.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
spinners = "4.1.1"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
cast_precision_loss = "allow"

[lints]
workspace = true
