[workspace]
members = ["crates/cli", "crates/lib"]
resolver = "3"

[workspace.package]
version = "0.1.3"
authors = ["Christoph Koehler <christoph@zerodeviation.net>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ckoehler/buddy-up"
readme = "README.md"

[workspace.dependencies]
buddy-up-lib = { version = "0.1.3", path = "crates/lib"}
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "ansi"] }
tracing-error = "0.2.1"

[workspace.lints.clippy]
# pedantic = { level = "deny", priority = -1 }
cast_precision_loss = "allow"
similar_names = "allow"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
