[package]
name = "buddy-up"
version = "0.1.2"
authors = ["Christoph Koehler <christoph@zerodeviation.net>"]
description = "Buddy up a changing group of people into unique pairs over time."
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ckoehler/buddy-up"
readme = "README.md"
publish = true


[dependencies]
anyhow = "1.0.96"
chrono = "0.4.39"
clap = { version = "4.5.30", features = ["derive"] }
comfy-table = "7.1.4"
csv = "1.3.1"
genetic_algorithm = "0.18.1"
glob = "0.3.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.139"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "ansi"] }
tracing-error = "0.2.1"

[[bin]]
name = "buddy"
path = "src/main.rs"


[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
cast_precision_loss = "allow"
similar_names = "allow"

[lints]
workspace = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
